# Generated by Django 2.2.6 on 2019-11-15 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sci_image', models.ImageField(upload_to='images/')),
                ('sci_bio', models.TextField()),
                ('sci_name', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
