# Generated by Django 2.2.6 on 2019-11-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='big_stuff',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scientist',
            name='sci_name',
            field=models.CharField(max_length=200),
        ),
    ]
