# Generated by Django 2.2.7 on 2019-12-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0005_scientist_sci_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sci_image', models.ImageField(upload_to='images/')),
                ('sci_name', models.CharField(max_length=200)),
                ('sci_bio', models.TextField()),
                ('sci_big_stuff', models.TextField()),
                ('sci_field', models.CharField(max_length=200)),
                ('sci_link', models.CharField(max_length=500)),
            ],
        ),
    ]
